export enum EBaseType {
  Weapons = "Weapons",
  MeleeWeapons = "MeleeWeapons",
  Swords = "Swords",
  Axes = "Axes",
  Scepters = "Scepters",
  Hammers = "Hammers",
  Maces = "Maces",
  Clubs = "Clubs",
  Polearms = "Polearms",
  Spears = "Spears",
  Katars = "Katars",
  Daggers = "Daggers",
  Staves = "Staves",
  Wands = "Wands",
  Mauls = "Mauls",
  MissileWeapons = "MissileWeapons",
  Bows = "Bows",
  Crossbows = "Crossbows",
  Throwing = "Throwing",
  Javelins = "Javelins",
  Orbs = "Orbs",
  ShrunkenHeads = "ShrunkenHeads",
  Pelts = "Pelts",

  Belts = "Belts",
  Gloves = "Gloves",
  Boots = "Boots",
  BarbHelms = "BarbHelms",
  BodyArmor = "BodyArmor",
  Shields = "Shields",
  Helms = "Helms",
  PaladinShields = "PaladinShields",
}

export const allBaseTypes: EBaseType[] = [
  EBaseType.Weapons,
  EBaseType.MissileWeapons,
  EBaseType.MeleeWeapons,
  EBaseType.Swords,
  EBaseType.Axes,
  EBaseType.Scepters,
  EBaseType.Hammers,
  EBaseType.Maces,
  EBaseType.Clubs,
  EBaseType.Polearms,
  EBaseType.Spears,
  EBaseType.Katars,
  EBaseType.Daggers,
  EBaseType.Staves,
  EBaseType.Wands,
  EBaseType.Orbs,

  EBaseType.BodyArmor,
  EBaseType.Helms,
  EBaseType.Pelts,
  EBaseType.Shields,
  EBaseType.PaladinShields,
  EBaseType.ShrunkenHeads,
];

export enum ECharacterClass {
  Amazon = "amazon",
  Sorceress = "sorceress",
  Necromancer = "necromancer",
  Paladin = "paladin",
  Barbarian = "barbarian",
  Druid = "druid",
  Assassin = "assassin",
}
