
export enum ERune {
    'El' = 'el',
    'Eld' = 'eld',
    'Tir' = 'tir',
    'Nef' = 'nef',
    'Eth' = 'eth',
    'Ith' = 'ith',
    'Tal' = 'tal',
    'Ral' = 'ral',
    'Ort' = 'ort',
    'Thul' = 'thul',
    'Amn' = 'amn',
    'Sol' = 'sol',
    'Shael' = 'shael',
    'Dol' = 'dol',
    'Hel' = 'hel',
    'Io' = 'io',
    'Lum' = 'lum',
    'Ko' = 'ko',
    'Fal' = 'fal',
    'Lem' = 'lem',
    'Pul' = 'pul',
    'Um' = 'um',
    'Mal' = 'mal',
    'Ist' = 'ist',
    'Gul' = 'gul',
    'Vex' = 'vex',
    'Ohm' = 'ohm',
    'Lo' = 'lo',
    'Sur' = 'sur',
    'Ber' = 'ber',
    'Jah' = 'jah',
    'Cham' = 'cham',
    'Zod' = 'zod'
}


export const runes = [
    ERune.El,
    ERune.Eld,
    ERune.Tir,
    ERune.Nef,
    ERune.Eth,
    ERune.Ith,
    ERune.Tal,
    ERune.Ral,
    ERune.Ort,
    ERune.Thul,
    ERune.Amn,
    ERune.Sol,
    ERune.Shael,
    ERune.Dol,
    ERune.Hel,
    ERune.Io,
    ERune.Lum,
    ERune.Ko,
    ERune.Fal,
    ERune.Lem,
    ERune.Pul,
    ERune.Um,
    ERune.Mal,
    ERune.Ist,
    ERune.Gul,
    ERune.Vex,
    ERune.Ohm,
    ERune.Lo,
    ERune.Sur,
    ERune.Ber,
    ERune.Jah,
    ERune.Cham,
    ERune.Zod
] as const;


export const runeMinLvl = {
    [ERune.El]: 11,
    [ERune.Eld]: 11,
    [ERune.Tir]: 13,
    [ERune.Nef]: 13,
    [ERune.Eth]: 15,
    [ERune.Ith]: 15,
    [ERune.Tal]: 17,
    [ERune.Ral]: 19,
    [ERune.Ort]: 21,
    [ERune.Thul]: 23,
    [ERune.Amn]: 25,
    [ERune.Sol]: 27,
    [ERune.Shael]: 29,
    [ERune.Dol]: 31,
    [ERune.Hel]: 0,
    [ERune.Io]: 35,
    [ERune.Lum]: 37,
    [ERune.Ko]: 39,
    [ERune.Fal]: 41,
    [ERune.Lem]: 43,
    [ERune.Pul]: 45,
    [ERune.Um]: 47,
    [ERune.Mal]: 49,
    [ERune.Ist]: 51,
    [ERune.Gul]: 53,
    [ERune.Vex]: 55,
    [ERune.Ohm]: 57,
    [ERune.Lo]: 59,
    [ERune.Sur]: 61,
    [ERune.Ber]: 63,
    [ERune.Jah]: 65,
    [ERune.Cham]: 67,
    [ERune.Zod]: 69,
}
