
export enum ERune {
    'El' = 'el',
    'Eld' = 'eld',
    'Tir' = 'tir',
    'Nef' = 'nef',
    'Eth' = 'eth',
    'Ith' = 'ith',
    'Tal' = 'tal',
    'Ral' = 'ral',
    'Ort' = 'ort',
    'Thul' = 'thul',
    'Amn' = 'amn',
    'Sol' = 'sol',
    'Shael' = 'shael',
    'Dol' = 'dol',
    'Hel' = 'hel',
    'Io' = 'io',
    'Lum' = 'lum',
    'Ko' = 'ko',
    'Fal' = 'fal',
    'Lem' = 'lem',
    'Pul' = 'pul',
    'Um' = 'um',
    'Mal' = 'mal',
    'Ist' = 'ist',
    'Gul' = 'gul',
    'Vex' = 'vex',
    'Ohm' = 'ohm',
    'Lo' = 'lo',
    'Sur' = 'sur',
    'Ber' = 'ber',
    'Jah' = 'jah',
    'Cham' = 'cham',
    'Zod' = 'zod'
}


export const runes = [
    ERune.El,
    ERune.Eld,
    ERune.Tir,
    ERune.Nef,
    ERune.Eth,
    ERune.Ith,
    ERune.Tal,
    ERune.Ral,
    ERune.Ort,
    ERune.Thul,
    ERune.Amn,
    ERune.Sol,
    ERune.Shael,
    ERune.Dol,
    ERune.Hel,
    ERune.Io,
    ERune.Lum,
    ERune.Ko,
    ERune.Fal,
    ERune.Lem,
    ERune.Pul,
    ERune.Um,
    ERune.Mal,
    ERune.Ist,
    ERune.Gul,
    ERune.Vex,
    ERune.Ohm,
    ERune.Lo,
    ERune.Sur,
    ERune.Ber,
    ERune.Jah,
    ERune.Cham,
    ERune.Zod
] as const;


export const runeMinLvl = {
    [ERune.El]: 11,
    [ERune.Eld]: 11,
    [ERune.Tir]: 13,
    [ERune.Nef]: 13,
    [ERune.Eth]: 15,
    [ERune.Ith]: 15,
    [ERune.Tal]: 17,
    [ERune.Ral]: 19,
    [ERune.Ort]: 21,
    [ERune.Thul]: 23,
    [ERune.Amn]: 25,
    [ERune.Sol]: 27,
    [ERune.Shael]: 29,
    [ERune.Dol]: 31,
    [ERune.Hel]: 0,
    [ERune.Io]: 35,
    [ERune.Lum]: 37,
    [ERune.Ko]: 39,
    [ERune.Fal]: 41,
    [ERune.Lem]: 43,
    [ERune.Pul]: 45,
    [ERune.Um]: 47,
    [ERune.Mal]: 49,
    [ERune.Ist]: 51,
    [ERune.Gul]: 53,
    [ERune.Vex]: 55,
    [ERune.Ohm]: 57,
    [ERune.Lo]: 59,
    [ERune.Sur]: 61,
    [ERune.Ber]: 63,
    [ERune.Jah]: 65,
    [ERune.Cham]: 67,
    [ERune.Zod]: 69,
}

export const idToRuneMapper: Record<number, ERune> = {
    10902: ERune.Io,
    10904: ERune.Shael,
    10906: ERune.Jah,
    20440: ERune.Zod,
    20441: ERune.Cham,
    20443: ERune.Ber,
    20444: ERune.Sur,
    20445: ERune.Lo,
    20446: ERune.Ohm,
    20447: ERune.Vex,
    20448: ERune.Gul,
    20449: ERune.Ist,
    20450: ERune.Mal,
    20451: ERune.Um,
    20452: ERune.Pul,
    20453: ERune.Lem,
    20454: ERune.Fal,
    20455: ERune.Ko,
    20456: ERune.Lum,
    20458: ERune.Hel,
    20459: ERune.Dol,
    20461: ERune.Sol,
    20462: ERune.Amn,
    20463: ERune.Thul,
    20464: ERune.Ort,
    20465: ERune.Ral,
    20466: ERune.Tal,
    20467: ERune.Ith,
    20468: ERune.Eth,
    20469: ERune.Nef,
    20470: ERune.Tir,
    20471: ERune.Eld,
    20472: ERune.El,
}

const idToRuneMapper2 = [
    {
        "id": 10902,
        "Key": "r16",
        "enUS": "Io Rune ÿc9(ÿc316ÿc9)",
    },
    {
        "id": 10904,
        "Key": "r13",
        "enUS": "Shael Rune ÿc9(ÿc313ÿc9)",
    },
    {
        "id": 10906,
        "Key": "r31",
        "enUS": "Jah\n~         Jah Rune ÿc9(ÿc131ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 10910,
        "Key": "Runeword22",
        "enUS": "Delirium",
    },
    {
        "id": 20440,
        "Key": "r33",
        "enUS": "\n~         Zod Rune ÿc9(ÿc133ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20441,
        "Key": "r32",
        "enUS": "\n~         Cham Rune ÿc9(ÿc132ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20443,
        "Key": "r30",
        "enUS": "Ber\n~         Ber Rune ÿc9(ÿc130ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20444,
        "Key": "r29",
        "enUS": "\n~         Sur Rune ÿc9(ÿc129ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20445,
        "Key": "r28",
        "enUS": "\n~         Lo Rune ÿc9(ÿc128ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20446,
        "Key": "r27",
        "enUS": "\n~         Ohm Rune ÿc9(ÿc127ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20447,
        "Key": "r26",
        "enUS": "\n~         Vex Rune ÿc9(ÿc126ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20448,
        "Key": "r25",
        "enUS": "\n~         Gul Rune ÿc9(ÿc125ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20449,
        "Key": "r24",
        "enUS": "\n~         Ist Rune ÿc9(ÿc824ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20450,
        "Key": "r23",
        "enUS": "\n~         Mal Rune ÿc9(ÿc823ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20451,
        "Key": "r22",
        "enUS": "\n~         Um Rune ÿc9(ÿc822ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20452,
        "Key": "r21",
        "enUS": "\n~         Pul Rune ÿc9(ÿc821ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20453,
        "Key": "r20",
        "enUS": "\n~         Lem Rune ÿc9(ÿc820ÿc9)         ~\nÿc;~         Pick  Me         ~ÿc0\n",
    },
    {
        "id": 20454,
        "Key": "r19",
        "enUS": "ÿcUFal Rune ÿc9(ÿc819ÿc9)\nÿc;•Pick  Up•ÿc0",
    },
    {
        "id": 20455,
        "Key": "r18",
        "enUS": "ÿcUKo Rune ÿc9(ÿc818ÿc9)\nÿc;•Pick  Up•ÿc0",
    },
    {
        "id": 20456,
        "Key": "r17",
        "enUS": "ÿcULum Rune ÿc9(ÿc817ÿc9)\nÿc;•Pick  Up•ÿc0",
    },
    {
        "id": 20458,
        "Key": "r15",
        "enUS": "Hel Rune ÿc9(ÿc315ÿc9)",
    },
    {
        "id": 20459,
        "Key": "r14",
        "enUS": "Dol Rune ÿc9(ÿc314ÿc9)",
    },
    {
        "id": 20461,
        "Key": "r12",
        "enUS": "Sol Rune ÿc9(ÿc312ÿc9)",
    },
    {
        "id": 20462,
        "Key": "r11",
        "enUS": "Amn Rune ÿc9(ÿc311ÿc9)",
    },
    {
        "id": 20463,
        "Key": "r10",
        "enUS": "Thul Rune ÿc9(ÿc310ÿc9)",
    },
    {
        "id": 20464,
        "Key": "r09",
        "enUS": "Ort Rune ÿc9(ÿc39ÿc9)",
    },
    {
        "id": 20465,
        "Key": "r08",
        "enUS": "Ral Rune ÿc9(ÿc08ÿc9)",
    },
    {
        "id": 20466,
        "Key": "r07",
        "enUS": "Tal Rune ÿc9(ÿc07ÿc9)",
    },
    {
        "id": 20467,
        "Key": "r06",
        "enUS": "Ith Rune ÿc9(ÿc06ÿc9)",
    },
    {
        "id": 20468,
        "Key": "r05",
        "enUS": "Eth Rune ÿc9(ÿc05ÿc9)",
    },
    {
        "id": 20469,
        "Key": "r04",
        "enUS": "Nef Rune ÿc9(ÿc04ÿc9)",
    },
    {
        "id": 20470,
        "Key": "r03",
        "enUS": "Tir Rune ÿc9(ÿc03ÿc9)",
    },
    {
        "id": 20471,
        "Key": "r02",
        "enUS": "Eld Rune ÿc9(ÿc02ÿc9)",
    },
    {
        "id": 20472,
        "Key": "r01",
        "enUS": "El Rune ÿc9(ÿc01ÿc9)",
    },
    {
        "id": 20473,
        "Key": "r33L",
        "enUS": "Zod",
    },
    {
        "id": 20474,
        "Key": "r32L",
        "enUS": "Cham",
    },
    {
        "id": 20476,
        "Key": "r30L",
        "enUS": "Ber",
    },
    {
        "id": 20477,
        "Key": "r29L",
        "enUS": "Sur",
    },
    {
        "id": 20478,
        "Key": "r28L",
        "enUS": "Lo",
    },
    {
        "id": 20479,
        "Key": "r27L",
        "enUS": "Ohm",
    },
    {
        "id": 20480,
        "Key": "r26L",
        "enUS": "Vex",
    },
    {
        "id": 20481,
        "Key": "r25L",
        "enUS": "Gul",
    },
    {
        "id": 20482,
        "Key": "r24L",
        "enUS": "Ist",
    },
    {
        "id": 20483,
        "Key": "r23L",
        "enUS": "Mal",
    },
    {
        "id": 20484,
        "Key": "r22L",
        "enUS": "Um",
    },
    {
        "id": 20485,
        "Key": "r21L",
        "enUS": "Pul",
    },
    {
        "id": 20486,
        "Key": "r20L",
        "enUS": "Lem",
    },
    {
        "id": 20487,
        "Key": "r19L",
        "enUS": "Fal",
    },
    {
        "id": 20488,
        "Key": "r18L",
        "enUS": "Ko",
    },
    {
        "id": 20489,
        "Key": "r17L",
        "enUS": "Lum",
    },
    {
        "id": 20491,
        "Key": "r15L",
        "enUS": "Hel",
    },
    {
        "id": 20492,
        "Key": "r14L",
        "enUS": "Dol",
    },
    {
        "id": 20494,
        "Key": "r12L",
        "enUS": "Sol",
    },
    {
        "id": 20495,
        "Key": "r11L",
        "enUS": "Amn",
    },
    {
        "id": 20496,
        "Key": "r10L",
        "enUS": "Thul",
    },
    {
        "id": 20497,
        "Key": "r09L",
        "enUS": "Ort",
    },
    {
        "id": 20498,
        "Key": "r08L",
        "enUS": "Ral",
    },
    {
        "id": 20499,
        "Key": "r07L",
        "enUS": "Tal",
    },
    {
        "id": 20500,
        "Key": "r06L",
        "enUS": "Ith",
    },
    {
        "id": 20501,
        "Key": "r05L",
        "enUS": "Eth",
    },
    {
        "id": 20502,
        "Key": "r04L",
        "enUS": "Nef",
    },
    {
        "id": 20503,
        "Key": "r03L",
        "enUS": "Tir",
    },
    {
        "id": 20504,
        "Key": "r02L",
        "enUS": "Eld",
    },
    {
        "id": 20505,
        "Key": "r01L",
        "enUS": "El",
    },
    {
        "id": 20506,
        "Key": "RuneQuote",
        "enUS": "'",
    },
    {
        "id": 20507,
        "Key": "Runeword1",
        "enUS": "Ancients' Pledge",
    },
    {
        "id": 20508,
        "Key": "Runeword2",
        "enUS": "Armageddon",
    },
    {
        "id": 20509,
        "Key": "Runeword3",
        "enUS": "Authority",
    },
    {
        "id": 20510,
        "Key": "Runeword4",
        "enUS": "Beast",
    },
    {
        "id": 20511,
        "Key": "Runeword5",
        "enUS": "Beauty",
    },
    {
        "id": 20512,
        "Key": "Runeword6",
        "enUS": "Black",
    },
    {
        "id": 20513,
        "Key": "Runeword7",
        "enUS": "Blood",
    },
    {
        "id": 20514,
        "Key": "Runeword8",
        "enUS": "Bone",
    },
    {
        "id": 20515,
        "Key": "Runeword9",
        "enUS": "Bramble",
    },
    {
        "id": 20516,
        "Key": "Runeword10",
        "enUS": "Brand",
    },
    {
        "id": 20517,
        "Key": "Runeword11",
        "enUS": "Breath of the Dying",
    },
    {
        "id": 20518,
        "Key": "Runeword12",
        "enUS": "Broken Promise",
    },
    {
        "id": 20519,
        "Key": "Runeword13",
        "enUS": "Call to Arms",
    },
    {
        "id": 20520,
        "Key": "Runeword14",
        "enUS": "Chains of Honor",
    },
    {
        "id": 20521,
        "Key": "Runeword15",
        "enUS": "Chance",
    },
    {
        "id": 20522,
        "Key": "Runeword16",
        "enUS": "Chaos",
    },
    {
        "id": 20523,
        "Key": "Runeword17",
        "enUS": "Crescent Moon",
    },
    {
        "id": 20524,
        "Key": "Runeword18",
        "enUS": "Darkness",
    },
    {
        "id": 20525,
        "Key": "Runeword19",
        "enUS": "Daylight",
    },
    {
        "id": 20526,
        "Key": "Runeword20",
        "enUS": "Death",
    },
    {
        "id": 20527,
        "Key": "Runeword21",
        "enUS": "Deception",
    },
    {
        "id": 20529,
        "Key": "Runeword23",
        "enUS": "Desire",
    },
    {
        "id": 20530,
        "Key": "Runeword24",
        "enUS": "Despair",
    },
    {
        "id": 20531,
        "Key": "Runeword25",
        "enUS": "Destruction",
    },
    {
        "id": 20532,
        "Key": "Runeword26",
        "enUS": "Doom",
    },
    {
        "id": 20533,
        "Key": "Runeword27",
        "enUS": "Dragon",
    },
    {
        "id": 20534,
        "Key": "Runeword28",
        "enUS": "Dread",
    },
    {
        "id": 20535,
        "Key": "Runeword29",
        "enUS": "Dream",
    },
    {
        "id": 20536,
        "Key": "Runeword30",
        "enUS": "Duress",
    },
    {
        "id": 20537,
        "Key": "Runeword31",
        "enUS": "Edge",
    },
    {
        "id": 20538,
        "Key": "Runeword32",
        "enUS": "Elation",
    },
    {
        "id": 20539,
        "Key": "Runeword33",
        "enUS": "Enigma",
    },
    {
        "id": 20540,
        "Key": "Runeword34",
        "enUS": "Enlightenment",
    },
    {
        "id": 20541,
        "Key": "Runeword35",
        "enUS": "Envy",
    },
    {
        "id": 20542,
        "Key": "Runeword36",
        "enUS": "Eternity",
    },
    {
        "id": 20543,
        "Key": "Runeword37",
        "enUS": "Exile",
    },
    {
        "id": 20544,
        "Key": "Runeword38",
        "enUS": "Faith",
    },
    {
        "id": 20545,
        "Key": "Runeword39",
        "enUS": "Famine",
    },
    {
        "id": 20546,
        "Key": "Runeword40",
        "enUS": "Flickering Flame",
    },
    {
        "id": 20547,
        "Key": "Runeword41",
        "enUS": "Fortitude",
    },
    {
        "id": 20548,
        "Key": "Runeword42",
        "enUS": "Fortune",
    },
    {
        "id": 20549,
        "Key": "Runeword43",
        "enUS": "Friendship",
    },
    {
        "id": 20550,
        "Key": "Runeword44",
        "enUS": "Fury",
    },
    {
        "id": 20551,
        "Key": "Runeword45",
        "enUS": "Gloom",
    },
    {
        "id": 20552,
        "Key": "Runeword46",
        "enUS": "Glory",
    },
    {
        "id": 20553,
        "Key": "Runeword47",
        "enUS": "Grief",
    },
    {
        "id": 20554,
        "Key": "Runeword48",
        "enUS": "Hand of Justice",
    },
    {
        "id": 20555,
        "Key": "Runeword49",
        "enUS": "Harmony",
    },
    {
        "id": 20556,
        "Key": "Runeword50",
        "enUS": "Hatred",
    },
    {
        "id": 20557,
        "Key": "Runeword51",
        "enUS": "Heart of the Oak",
    },
    {
        "id": 20558,
        "Key": "Runeword52",
        "enUS": "Heaven's Will",
    },
    {
        "id": 20559,
        "Key": "Runeword53",
        "enUS": "Holy Tears",
    },
    {
        "id": 20560,
        "Key": "Runeword54",
        "enUS": "Holy Thunder",
    },
    {
        "id": 20561,
        "Key": "Runeword55",
        "enUS": "Honor",
    },
    {
        "id": 20562,
        "Key": "Runeword56",
        "enUS": "Revenge",
    },
    {
        "id": 20563,
        "Key": "Runeword57",
        "enUS": "Humility",
    },
    {
        "id": 20564,
        "Key": "Runeword58",
        "enUS": "Hunger",
    },
    {
        "id": 20565,
        "Key": "Runeword59",
        "enUS": "Ice",
    },
    {
        "id": 20566,
        "Key": "Runeword60",
        "enUS": "Infinity",
    },
    {
        "id": 20567,
        "Key": "Runeword61",
        "enUS": "Innocence",
    },
    {
        "id": 20568,
        "Key": "Runeword62",
        "enUS": "Insight",
    },
    {
        "id": 20569,
        "Key": "Runeword63",
        "enUS": "Jealousy",
    },
    {
        "id": 20570,
        "Key": "Runeword64",
        "enUS": "Judgement",
    },
    {
        "id": 20571,
        "Key": "Runeword65",
        "enUS": "King's Grace",
    },
    {
        "id": 20572,
        "Key": "Runeword66",
        "enUS": "Kingslayer",
    },
    {
        "id": 20573,
        "Key": "Runeword67",
        "enUS": "Knight's Vigil",
    },
    {
        "id": 20574,
        "Key": "Runeword68",
        "enUS": "Knowledge",
    },
    {
        "id": 20575,
        "Key": "Runeword69",
        "enUS": "Last Wish",
    },
    {
        "id": 20576,
        "Key": "Runeword70",
        "enUS": "Law",
    },
    {
        "id": 20577,
        "Key": "Runeword71",
        "enUS": "Lawbringer",
    },
    {
        "id": 20578,
        "Key": "Runeword72",
        "enUS": "Leaf",
    },
    {
        "id": 20579,
        "Key": "Runeword73",
        "enUS": "Lightning",
    },
    {
        "id": 20580,
        "Key": "Runeword74",
        "enUS": "Lionheart",
    },
    {
        "id": 20581,
        "Key": "Runeword75",
        "enUS": "Lore",
    },
    {
        "id": 20582,
        "Key": "Runeword76",
        "enUS": "Love",
    },
    {
        "id": 20583,
        "Key": "Runeword77",
        "enUS": "Loyalty",
    },
    {
        "id": 20584,
        "Key": "Runeword78",
        "enUS": "Lust",
    },
    {
        "id": 20585,
        "Key": "Runeword79",
        "enUS": "Madness",
    },
    {
        "id": 20586,
        "Key": "Runeword81",
        "enUS": "Malice",
    },
    {
        "id": 20587,
        "Key": "Runeword82",
        "enUS": "Melody",
    },
    {
        "id": 20588,
        "Key": "Runeword83",
        "enUS": "Memory",
    },
    {
        "id": 20589,
        "Key": "Runeword84",
        "enUS": "Mist",
    },
    {
        "id": 20590,
        "Key": "Runeword85",
        "enUS": "Morning",
    },
    {
        "id": 20591,
        "Key": "Runeword86",
        "enUS": "Mystery",
    },
    {
        "id": 20592,
        "Key": "Runeword87",
        "enUS": "Myth",
    },
    {
        "id": 20593,
        "Key": "Runeword88",
        "enUS": "Nadir",
    },
    {
        "id": 20594,
        "Key": "Runeword89",
        "enUS": "Nature's Kingdom",
    },
    {
        "id": 20595,
        "Key": "Runeword90",
        "enUS": "Night",
    },
    {
        "id": 20596,
        "Key": "Runeword91",
        "enUS": "Oath",
    },
    {
        "id": 20597,
        "Key": "Runeword92",
        "enUS": "Obedience",
    },
    {
        "id": 20598,
        "Key": "Runeword93",
        "enUS": "Oblivion",
    },
    {
        "id": 20599,
        "Key": "Runeword94",
        "enUS": "Obsession",
    },
    {
        "id": 20600,
        "Key": "Runeword95",
        "enUS": "Passion",
    },
    {
        "id": 20601,
        "Key": "Runeword96",
        "enUS": "Patience",
    },
    {
        "id": 20602,
        "Key": "Runeword97",
        "enUS": "Pattern",
    },
    {
        "id": 20603,
        "Key": "Runeword98",
        "enUS": "Peace",
    },
    {
        "id": 20604,
        "Key": "Runeword99",
        "enUS": "Voice of Reason",
    },
    {
        "id": 20605,
        "Key": "Runeword100",
        "enUS": "Penitence",
    },
    {
        "id": 20606,
        "Key": "Runeword101",
        "enUS": "Peril",
    },
    {
        "id": 20607,
        "Key": "Runeword102",
        "enUS": "Pestilence",
    },
    {
        "id": 20608,
        "Key": "Runeword103",
        "enUS": "Phoenix",
    },
    {
        "id": 20609,
        "Key": "Runeword104",
        "enUS": "Piety",
    },
    {
        "id": 20610,
        "Key": "Runeword105",
        "enUS": "Pillar of Faith",
    },
    {
        "id": 20611,
        "Key": "Runeword106",
        "enUS": "Plague",
    },
    {
        "id": 20612,
        "Key": "Runeword107",
        "enUS": "Praise",
    },
    {
        "id": 20613,
        "Key": "Runeword108",
        "enUS": "Prayer",
    },
    {
        "id": 20614,
        "Key": "Runeword109",
        "enUS": "Pride",
    },
    {
        "id": 20615,
        "Key": "Runeword110",
        "enUS": "Principle",
    },
    {
        "id": 20616,
        "Key": "Runeword111",
        "enUS": "Prowess in Battle",
    },
    {
        "id": 20617,
        "Key": "Runeword112",
        "enUS": "Prudence",
    },
    {
        "id": 20618,
        "Key": "Runeword113",
        "enUS": "Punishment",
    },
    {
        "id": 20619,
        "Key": "Runeword114",
        "enUS": "Purity",
    },
    {
        "id": 20620,
        "Key": "Runeword115",
        "enUS": "Question",
    },
    {
        "id": 20621,
        "Key": "Runeword116",
        "enUS": "Radiance",
    },
    {
        "id": 20622,
        "Key": "Runeword117",
        "enUS": "Rain",
    },
    {
        "id": 20623,
        "Key": "Runeword118",
        "enUS": "Reason",
    },
    {
        "id": 20624,
        "Key": "Runeword119",
        "enUS": "Red",
    },
    {
        "id": 20625,
        "Key": "Runeword120",
        "enUS": "Rhyme",
    },
    {
        "id": 20626,
        "Key": "Runeword121",
        "enUS": "Rift",
    },
    {
        "id": 20627,
        "Key": "Runeword122",
        "enUS": "Sanctuary",
    },
    {
        "id": 20628,
        "Key": "Runeword123",
        "enUS": "Serendipity",
    },
    {
        "id": 20629,
        "Key": "Runeword124",
        "enUS": "Shadow",
    },
    {
        "id": 20630,
        "Key": "Runeword125",
        "enUS": "Shadow of Doubt",
    },
    {
        "id": 20631,
        "Key": "Runeword126",
        "enUS": "Silence",
    },
    {
        "id": 20632,
        "Key": "Runeword127",
        "enUS": "Siren's Song",
    },
    {
        "id": 20633,
        "Key": "Runeword128",
        "enUS": "Smoke",
    },
    {
        "id": 20634,
        "Key": "Runeword129",
        "enUS": "Sorrow",
    },
    {
        "id": 20635,
        "Key": "Runeword130",
        "enUS": "Spirit",
    },
    {
        "id": 20636,
        "Key": "Runeword131",
        "enUS": "Splendor",
    },
    {
        "id": 20637,
        "Key": "Runeword132",
        "enUS": "Starlight",
    },
    {
        "id": 20638,
        "Key": "Runeword133",
        "enUS": "Stealth",
    },
    {
        "id": 20639,
        "Key": "Runeword134",
        "enUS": "Steel",
    },
    {
        "id": 20640,
        "Key": "Runeword135",
        "enUS": "Still Water",
    },
    {
        "id": 20641,
        "Key": "Runeword136",
        "enUS": "Sting",
    },
    {
        "id": 20642,
        "Key": "Runeword137",
        "enUS": "Stone",
    },
    {
        "id": 20643,
        "Key": "Runeword138",
        "enUS": "Storm",
    },
    {
        "id": 20644,
        "Key": "Runeword139",
        "enUS": "Strength",
    },
    {
        "id": 20645,
        "Key": "Runeword140",
        "enUS": "Tempest",
    },
    {
        "id": 20646,
        "Key": "Runeword141",
        "enUS": "Temptation",
    },
    {
        "id": 20647,
        "Key": "Runeword142",
        "enUS": "Terror",
    },
    {
        "id": 20648,
        "Key": "Runeword143",
        "enUS": "Thirst",
    },
    {
        "id": 20649,
        "Key": "Runeword144",
        "enUS": "Thought",
    },
    {
        "id": 20650,
        "Key": "Runeword145",
        "enUS": "Thunder",
    },
    {
        "id": 20651,
        "Key": "Runeword146",
        "enUS": "Time",
    },
    {
        "id": 20652,
        "Key": "Runeword147",
        "enUS": "Tradition",
    },
    {
        "id": 20653,
        "Key": "Runeword148",
        "enUS": "Treachery",
    },
    {
        "id": 20654,
        "Key": "Runeword149",
        "enUS": "Trust",
    },
    {
        "id": 20655,
        "Key": "Runeword150",
        "enUS": "Truth",
    },
    {
        "id": 20656,
        "Key": "Runeword151",
        "enUS": "Unbending Will",
    },
    {
        "id": 20657,
        "Key": "Runeword152",
        "enUS": "Valor",
    },
    {
        "id": 20658,
        "Key": "Runeword153",
        "enUS": "Vengeance",
    },
    {
        "id": 20659,
        "Key": "Runeword154",
        "enUS": "Venom",
    },
    {
        "id": 20660,
        "Key": "Runeword155",
        "enUS": "Victory",
    },
    {
        "id": 20661,
        "Key": "Runeword156",
        "enUS": "Voice",
    },
    {
        "id": 20662,
        "Key": "Runeword157",
        "enUS": "Void",
    },
    {
        "id": 20663,
        "Key": "Runeword158",
        "enUS": "War",
    },
    {
        "id": 20664,
        "Key": "Runeword159",
        "enUS": "Water",
    },
    {
        "id": 20665,
        "Key": "Runeword160",
        "enUS": "Wealth",
    },
    {
        "id": 20666,
        "Key": "Runeword161",
        "enUS": "Whisper",
    },
    {
        "id": 20667,
        "Key": "Runeword162",
        "enUS": "White",
    },
    {
        "id": 20668,
        "Key": "Runeword163",
        "enUS": "Wind",
    },
    {
        "id": 20669,
        "Key": "Runeword164",
        "enUS": "Wings of Hope",
    },
    {
        "id": 20670,
        "Key": "Runeword165",
        "enUS": "Wisdom",
    },
    {
        "id": 20671,
        "Key": "Runeword166",
        "enUS": "Woe",
    },
    {
        "id": 20672,
        "Key": "Runeword167",
        "enUS": "Wonder",
    },
    {
        "id": 20673,
        "Key": "Runeword168",
        "enUS": "Wrath",
    },
    {
        "id": 20674,
        "Key": "Runeword169",
        "enUS": "Youth",
    },
    {
        "id": 20675,
        "Key": "Runeword170",
        "enUS": "Zephyr",
    },
    {
        "id": 27360,
        "Key": "Runeword171",
        "enUS": "Hustle",
    },
    {
        "id": 27361,
        "Key": "Runeword172",
        "enUS": "Hustle",
    },
    {
        "id": 27362,
        "Key": "Runeword173",
        "enUS": "Mosaic",
    },
    {
        "id": 27363,
        "Key": "Runeword174",
        "enUS": "Metamorphosis",
    },
    {
        "id": 27364,
        "Key": "Runeword175",
        "enUS": "Ground",
    },
    {
        "id": 27365,
        "Key": "Runeword176",
        "enUS": "Temper",
    },
    {
        "id": 27366,
        "Key": "Runeword177",
        "enUS": "Hearth",
    },
    {
        "id": 27367,
        "Key": "Runeword178",
        "enUS": "Cure",
    },
    {
        "id": 27368,
        "Key": "Runeword179",
        "enUS": "Bulwark",
    }
]