// Enum для обычных предметов
export enum ECommonItem {
  "arrows" = "arrows",
  "bolts" = "bolts",
  "staminaPotions" = "staminaPotions",
  "antidotes" = "antidotes",
  "thawingPotions" = "thawingPotions",
  "amulets" = "amulets",
  "rings" = "rings",
  "jewels" = "jewels",
  "smallCharms" = "smallCharms",
  "largeCharms" = "largeCharms",
  "grandCharms" = "grandCharms",
  "gold" = "gold",
  "keys" = "keys",
  "hp1" = "hp1",
  "hp2" = "hp2",
  "hp3" = "hp3",
  "hp4" = "hp4",
  "hp5" = "hp5",
  "mp1" = "mp1",
  "mp2" = "mp2",
  "mp3" = "mp3",
  "mp4" = "mp4",
  "mp5" = "mp5",
  "rej1" = "rej1",
  "rej2" = "rej2",
  "identify1" = "identify1",
  "identify2" = "identify2",
  "portal1" = "portal1",
  "portal2" = "portal2",
  "keyTerror" = "keyTerror",
  "keyHate" = "keyHate",
  "keyDestruction" = "keyDestruction",
  "essenceHatred" = "essenceHatred",
  "essenceSuffering" = "essenceSuffering",
  "essenceTerror" = "essenceTerror",
  "essenceDestruction" = "essenceDestruction",
  "tokenAbsolution" = "tokenAbsolution",
  "pPoison1" = "pPoison1", // Strangling Gas Potion
  "pPoison2" = "pPoison2", // Choking Gas Potion
  "pPoison3" = "pPoison3", // Rancid Gas Potion
  "pFire1" = "pFire1", // Fulminating Potion
  "pFire2" = "pFire2", // Exploding Potion
  "pFire3" = "pFire3", // Oil Potion
}

// Маппинг ID к предметам
export const idToCommonItemMapper: Record<number, ECommonItem> = {
  2218: ECommonItem.arrows,
  2220: ECommonItem.bolts,
  2207: ECommonItem.staminaPotions,
  2208: ECommonItem.antidotes,
  2211: ECommonItem.thawingPotions,
  2212: ECommonItem.amulets,
  2214: ECommonItem.rings,
  20433: ECommonItem.jewels,
  20435: ECommonItem.smallCharms,
  20436: ECommonItem.largeCharms,
  20437: ECommonItem.grandCharms,
  2215: ECommonItem.gold,
  2222: ECommonItem.keys,
  2266: ECommonItem.hp1,
  2267: ECommonItem.hp2,
  2268: ECommonItem.hp3,
  2269: ECommonItem.hp4,
  2270: ECommonItem.hp5,
  2271: ECommonItem.mp1,
  2272: ECommonItem.mp2,
  2273: ECommonItem.mp3,
  2274: ECommonItem.mp4,
  2275: ECommonItem.mp5,
  2209: ECommonItem.rej1,
  2210: ECommonItem.rej2,
  2202: ECommonItem.identify1,
  2201: ECommonItem.identify2,
  2200: ECommonItem.portal1,
  2199: ECommonItem.portal2,
  11146: ECommonItem.keyTerror,
  11147: ECommonItem.keyHate,
  11148: ECommonItem.keyDestruction,
  11165: ECommonItem.essenceHatred,
  11164: ECommonItem.essenceSuffering,
  11166: ECommonItem.essenceTerror,
  11167: ECommonItem.essenceDestruction,
  11163: ECommonItem.tokenAbsolution,
  2182: ECommonItem.pPoison1,
  2184: ECommonItem.pPoison2,
  2186: ECommonItem.pPoison3,
  2183: ECommonItem.pFire1,
  2185: ECommonItem.pFire2,
  2187: ECommonItem.pFire3,
};

// Обратный маппинг для записи
export const commonItemToIdMapper: Record<ECommonItem, number> = {
  [ECommonItem.arrows]: 2218,
  [ECommonItem.bolts]: 2220,
  [ECommonItem.staminaPotions]: 2207,
  [ECommonItem.antidotes]: 2208,
  [ECommonItem.thawingPotions]: 2211,
  [ECommonItem.amulets]: 2212,
  [ECommonItem.rings]: 2214,
  [ECommonItem.jewels]: 20433,
  [ECommonItem.smallCharms]: 20435,
  [ECommonItem.largeCharms]: 20436,
  [ECommonItem.grandCharms]: 20437,
  [ECommonItem.gold]: 2215,
  [ECommonItem.keys]: 2222,
  [ECommonItem.hp1]: 2266,
  [ECommonItem.hp2]: 2267,
  [ECommonItem.hp3]: 2268,
  [ECommonItem.hp4]: 2269,
  [ECommonItem.hp5]: 2270,
  [ECommonItem.mp1]: 2271,
  [ECommonItem.mp2]: 2272,
  [ECommonItem.mp3]: 2273,
  [ECommonItem.mp4]: 2274,
  [ECommonItem.mp5]: 2275,
  [ECommonItem.rej1]: 2209,
  [ECommonItem.rej2]: 2210,
  [ECommonItem.identify1]: 2202,
  [ECommonItem.identify2]: 2201,
  [ECommonItem.portal1]: 2200,
  [ECommonItem.portal2]: 2199,
  [ECommonItem.keyTerror]: 11146,
  [ECommonItem.keyHate]: 11147,
  [ECommonItem.keyDestruction]: 11148,
  [ECommonItem.essenceHatred]: 11165,
  [ECommonItem.essenceSuffering]: 11164,
  [ECommonItem.essenceTerror]: 11166,
  [ECommonItem.essenceDestruction]: 11167,
  [ECommonItem.tokenAbsolution]: 11163,
  [ECommonItem.pPoison1]: 2182,
  [ECommonItem.pPoison2]: 2184,
  [ECommonItem.pPoison3]: 2186,
  [ECommonItem.pFire1]: 2183,
  [ECommonItem.pFire2]: 2185,
  [ECommonItem.pFire3]: 2187,
};

// Группировка предметов по типам
export const commonItemGroups = {
  simple: [
    ECommonItem.arrows,
    ECommonItem.bolts,
    ECommonItem.staminaPotions,
    ECommonItem.antidotes,
    ECommonItem.thawingPotions,
    ECommonItem.amulets,
    ECommonItem.rings,
    ECommonItem.jewels,
    ECommonItem.smallCharms,
    ECommonItem.largeCharms,
    ECommonItem.grandCharms,
    ECommonItem.gold,
    ECommonItem.keys,
  ],
  healthPotions: [
    ECommonItem.hp1,
    ECommonItem.hp2,
    ECommonItem.hp3,
    ECommonItem.hp4,
    ECommonItem.hp5,
  ],
  manaPotions: [
    ECommonItem.mp1,
    ECommonItem.mp2,
    ECommonItem.mp3,
    ECommonItem.mp4,
    ECommonItem.mp5,
  ],
  rejuvenationPotions: [ECommonItem.rej1, ECommonItem.rej2],
  identify: [ECommonItem.identify1, ECommonItem.identify2],
  portal: [ECommonItem.portal1, ECommonItem.portal2],
  uberKeys: [
    ECommonItem.keyTerror,
    ECommonItem.keyHate,
    ECommonItem.keyDestruction,
  ],
  essences: [
    ECommonItem.essenceHatred,
    ECommonItem.essenceSuffering,
    ECommonItem.essenceTerror,
    ECommonItem.essenceDestruction,
    ECommonItem.tokenAbsolution,
  ],
  poisonPotions: [
    ECommonItem.pPoison1,
    ECommonItem.pPoison2,
    ECommonItem.pPoison3,
  ],
  firePotions: [ECommonItem.pFire1, ECommonItem.pFire2, ECommonItem.pFire3],
};

// Маппинг для получения ECommonItem из настроек
export const settingsKeyToCommonItemMapper = {
  arrows: ECommonItem.arrows,
  bolts: ECommonItem.bolts,
  staminaPotions: ECommonItem.staminaPotions,
  antidotes: ECommonItem.antidotes,
  thawingPotions: ECommonItem.thawingPotions,
  amulets: ECommonItem.amulets,
  rings: ECommonItem.rings,
  jewels: ECommonItem.jewels,
  smallCharms: ECommonItem.smallCharms,
  largeCharms: ECommonItem.largeCharms,
  grandCharms: ECommonItem.grandCharms,
  gold: ECommonItem.gold,
  keys: ECommonItem.keys,
  healthPotions: commonItemGroups.healthPotions,
  manaPotions: commonItemGroups.manaPotions,
  rejuvenationPotions: commonItemGroups.rejuvenationPotions,
  identify: commonItemGroups.identify,
  portal: commonItemGroups.portal,
  uberKeys: commonItemGroups.uberKeys,
  essences: commonItemGroups.essences,
  poisonPotions: commonItemGroups.poisonPotions,
  firePotions: commonItemGroups.firePotions,
};

// В каком файле хранится локализация конкретного предмета
export const commonItemFileMapper: Record<
  ECommonItem,
  "item-names" | "item-nameaffixes" | "item-modifiers"
> = {
  [ECommonItem.arrows]: "item-names",
  [ECommonItem.bolts]: "item-names",
  [ECommonItem.staminaPotions]: "item-names",
  [ECommonItem.antidotes]: "item-names",
  [ECommonItem.thawingPotions]: "item-names",
  [ECommonItem.amulets]: "item-names",
  [ECommonItem.rings]: "item-names",
  [ECommonItem.jewels]: "item-names",
  [ECommonItem.smallCharms]: "item-names",
  [ECommonItem.largeCharms]: "item-names",
  [ECommonItem.grandCharms]: "item-names",
  [ECommonItem.gold]: "item-nameaffixes",
  [ECommonItem.keys]: "item-names",
  [ECommonItem.hp1]: "item-names",
  [ECommonItem.hp2]: "item-names",
  [ECommonItem.hp3]: "item-names",
  [ECommonItem.hp4]: "item-names",
  [ECommonItem.hp5]: "item-names",
  [ECommonItem.mp1]: "item-names",
  [ECommonItem.mp2]: "item-names",
  [ECommonItem.mp3]: "item-names",
  [ECommonItem.mp4]: "item-names",
  [ECommonItem.mp5]: "item-names",
  [ECommonItem.rej1]: "item-names",
  [ECommonItem.rej2]: "item-names",
  [ECommonItem.identify1]: "item-names",
  [ECommonItem.identify2]: "item-names",
  [ECommonItem.portal1]: "item-names",
  [ECommonItem.portal2]: "item-names",
  [ECommonItem.keyTerror]: "item-names",
  [ECommonItem.keyHate]: "item-names",
  [ECommonItem.keyDestruction]: "item-names",
  [ECommonItem.essenceHatred]: "item-names",
  [ECommonItem.essenceSuffering]: "item-names",
  [ECommonItem.essenceTerror]: "item-names",
  [ECommonItem.essenceDestruction]: "item-names",
  [ECommonItem.tokenAbsolution]: "item-modifiers",
  [ECommonItem.pPoison1]: "item-names",
  [ECommonItem.pPoison2]: "item-names",
  [ECommonItem.pPoison3]: "item-names",
  [ECommonItem.pFire1]: "item-names",
  [ECommonItem.pFire2]: "item-names",
  [ECommonItem.pFire3]: "item-names",
};
