export const colorCodes = {
  white: "ÿc0",
  gray: "ÿc5",
  black: "ÿc6",
  beige: "ÿcM",
  lightred: "ÿc1",
  red: "ÿcU",
  dimred: "ÿcS",
  orange: "ÿc@",
  lightgold: "ÿc7",
  yellow: "ÿc9",
  lightyellow: "ÿcR",
  green: "ÿc2",
  dimgreen: "ÿcA",
  darkgreen: "ÿc:",
  indigo: "ÿc3",
  lightindigo: "ÿcP",
  turquoise: "ÿcN",
  lightblue: "ÿcT",
  pink: "ÿcO",
  purple: "ÿc;",
};
