
export enum ERune {
  'El' = 'el',
  'Eld' = 'eld',
  'Tir' = 'tir',
  'Nef' = 'nef',
  'Eth' = 'eth',
  'Ith' = 'ith',
  'Tal' = 'tal',
  'Ral' = 'ral',
  'Ort' = 'ort',
  'Thul' = 'thul',
  'Amn' = 'amn',
  'Sol' = 'sol',
  'Shael' = 'shael',
  'Dol' = 'dol',
  'Hel' = 'hel',
  'Io' = 'io',
  'Lum' = 'lum',
  'Ko' = 'ko',
  'Fal' = 'fal',
  'Lem' = 'lem',
  'Pul' = 'pul',
  'Um' = 'um',
  'Mal' = 'mal',
  'Ist' = 'ist',
  'Gul' = 'gul',
  'Vex' = 'vex',
  'Ohm' = 'ohm',
  'Lo' = 'lo',
  'Sur' = 'sur',
  'Ber' = 'ber',
  'Jah' = 'jah',
  'Cham' = 'cham',
  'Zod' = 'zod'
}


export const runes = [
  ERune.El,
  ERune.Eld,
  ERune.Tir,
  ERune.Nef,
  ERune.Eth,
  ERune.Ith,
  ERune.Tal,
  ERune.Ral,
  ERune.Ort,
  ERune.Thul,
  ERune.Amn,
  ERune.Sol,
  ERune.Shael,
  ERune.Dol,
  ERune.Hel,
  ERune.Io,
  ERune.Lum,
  ERune.Ko,
  ERune.Fal,
  ERune.Lem,
  ERune.Pul,
  ERune.Um,
  ERune.Mal,
  ERune.Ist,
  ERune.Gul,
  ERune.Vex,
  ERune.Ohm,
  ERune.Lo,
  ERune.Sur,
  ERune.Ber,
  ERune.Jah,
  ERune.Cham,
  ERune.Zod
] as const;


export const runeMinLvl = {
  [ERune.El]: 11,
  [ERune.Eld]: 11,
  [ERune.Tir]: 13,
  [ERune.Nef]: 13,
  [ERune.Eth]: 15,
  [ERune.Ith]: 15,
  [ERune.Tal]: 17,
  [ERune.Ral]: 19,
  [ERune.Ort]: 21,
  [ERune.Thul]: 23,
  [ERune.Amn]: 25,
  [ERune.Sol]: 27,
  [ERune.Shael]: 29,
  [ERune.Dol]: 31,
  [ERune.Hel]: 0,
  [ERune.Io]: 35,
  [ERune.Lum]: 37,
  [ERune.Ko]: 39,
  [ERune.Fal]: 41,
  [ERune.Lem]: 43,
  [ERune.Pul]: 45,
  [ERune.Um]: 47,
  [ERune.Mal]: 49,
  [ERune.Ist]: 51,
  [ERune.Gul]: 53,
  [ERune.Vex]: 55,
  [ERune.Ohm]: 57,
  [ERune.Lo]: 59,
  [ERune.Sur]: 61,
  [ERune.Ber]: 63,
  [ERune.Jah]: 65,
  [ERune.Cham]: 67,
  [ERune.Zod]: 69,
}

export const idToRuneMapper: Record<number, ERune> = {
  10902: ERune.Io,
  10904: ERune.Shael,
  10906: ERune.Jah,
  20440: ERune.Zod,
  20441: ERune.Cham,
  20443: ERune.Ber,
  20444: ERune.Sur,
  20445: ERune.Lo,
  20446: ERune.Ohm,
  20447: ERune.Vex,
  20448: ERune.Gul,
  20449: ERune.Ist,
  20450: ERune.Mal,
  20451: ERune.Um,
  20452: ERune.Pul,
  20453: ERune.Lem,
  20454: ERune.Fal,
  20455: ERune.Ko,
  20456: ERune.Lum,
  20458: ERune.Hel,
  20459: ERune.Dol,
  20461: ERune.Sol,
  20462: ERune.Amn,
  20463: ERune.Thul,
  20464: ERune.Ort,
  20465: ERune.Ral,
  20466: ERune.Tal,
  20467: ERune.Ith,
  20468: ERune.Eth,
  20469: ERune.Nef,
  20470: ERune.Tir,
  20471: ERune.Eld,
  20472: ERune.El,
}

export const runeNumbers = {
  [ERune.El]: 1,
  [ERune.Eld]: 2,
  [ERune.Tir]: 3,
  [ERune.Nef]: 4,
  [ERune.Eth]: 5,
  [ERune.Ith]: 6,
  [ERune.Tal]: 7,
  [ERune.Ral]: 8,
  [ERune.Ort]: 9,
  [ERune.Thul]: 10,
  [ERune.Amn]: 11,
  [ERune.Sol]: 12,
  [ERune.Shael]: 13,
  [ERune.Dol]: 14,
  [ERune.Hel]: 15,
  [ERune.Io]: 16,
  [ERune.Lum]: 17,
  [ERune.Ko]: 18,
  [ERune.Fal]: 19,
  [ERune.Lem]: 20,
  [ERune.Pul]: 21,
  [ERune.Um]: 22,
  [ERune.Mal]: 23,
  [ERune.Ist]: 24,
  [ERune.Gul]: 25,
  [ERune.Vex]: 26,
  [ERune.Ohm]: 27,
  [ERune.Lo]: 28,
  [ERune.Sur]: 29,
  [ERune.Ber]: 30,
  [ERune.Jah]: 31,
  [ERune.Cham]: 32,
  [ERune.Zod]: 33,
}

// Захардкоженные переводы рун для автоматического режима
export const runeHardcodedLocales = {
  [ERune.El]: {
    enUS: "El Rune",
    "zhTW": "符文：艾爾",
    "deDE": "[fs]El-Rune",
    "esES": "Runa El",
    "frFR": "[fs]Rune El",
    "itIT": "[fs]Runa El",
    "koKR": "엘 룬",
    "plPL": "Runa El",
    "esMX": "Runa El",
    "jaJP": "エル・ルーン",
    "ptBR": "Runa El",
    "ruRU": "Руна Эль",
    "zhCN": "艾尔符文"
  },
  [ERune.Eld]: {
    enUS: "Eld Rune",
    "zhTW": "符文：艾德",
    "deDE": "[fs]Eld-Rune",
    "esES": "Runa Eld",
    "frFR": "[fs]Rune Eld",
    "itIT": "[fs]Runa Eld",
    "koKR": "엘드 룬",
    "plPL": "Runa Eld",
    "esMX": "Runa Eld",
    "jaJP": "エルド・ルーン",
    "ptBR": "Runa Eld",
    "ruRU": "Руна Элд",
    "zhCN": "艾德符文"
  },
  [ERune.Tir]: {
    enUS: "Tir Rune",
    "zhTW": "符文：特爾",
    "deDE": "[fs]Tir-Rune",
    "esES": "Runa Tir",
    "frFR": "[fs]Rune Tir",
    "itIT": "[fs]Runa Tir",
    "koKR": "티르 룬",
    "plPL": "Runa Tir",
    "esMX": "Runa Tir",
    "jaJP": "ティア・ルーン",
    "ptBR": "Runa Tir",
    "ruRU": "Руна Тир",
    "zhCN": "提尔符文"
  },
  [ERune.Nef]: {
    enUS: "Nef Rune",
    "zhTW": "符文：那夫",
    "deDE": "[fs]Nef-Rune",
    "esES": "Runa Nef",
    "frFR": "[fs]Rune Nef",
    "itIT": "[fs]Runa Nef",
    "koKR": "네프 룬",
    "plPL": "Runa Nef",
    "esMX": "Runa Nef",
    "jaJP": "ネフ・ルーン",
    "ptBR": "Runa Nef",
    "ruRU": "Руна Неф",
    "zhCN": "奈夫符文"
  },
  [ERune.Eth]: {
    enUS: "Eth Rune",
    "zhTW": "符文：愛斯",
    "deDE": "[fs]Eth-Rune",
    "esES": "Runa Eth",
    "frFR": "[fs]Rune Eth",
    "itIT": "[fs]Runa Eth",
    "koKR": "에드 룬",
    "plPL": "Runa Eth",
    "esMX": "Runa Eth",
    "jaJP": "エス・ルーン",
    "ptBR": "Runa Eth",
    "ruRU": "Руна Эт",
    "zhCN": "艾斯符文"
  },
  [ERune.Ith]: {
    enUS: "Ith Rune",
    "zhTW": "符文：伊司",
    "deDE": "[fs]Ith-Rune",
    "esES": "Runa Ith",
    "frFR": "[fs]Rune Ith",
    "itIT": "[fs]Runa Ith",
    "koKR": "아이드 룬",
    "plPL": "Runa Ith",
    "esMX": "Runa Ith",
    "jaJP": "イス・ルーン",
    "ptBR": "Runa Ith",
    "ruRU": "Руна Ит",
    "zhCN": "伊司符文"
  },
  [ERune.Tal]: {
    enUS: "Tal Rune",
    "zhTW": "符文：塔爾",
    "deDE": "[fs]Tal-Rune",
    "esES": "Runa Tal",
    "frFR": "[fs]Rune Tal",
    "itIT": "[fs]Runa Tal",
    "koKR": "탈 룬",
    "plPL": "Runa Tal",
    "esMX": "Runa Tal",
    "jaJP": "タル・ルーン",
    "ptBR": "Runa Tal",
    "ruRU": "Руна Тал",
    "zhCN": "塔尔符文"
  },
  [ERune.Ral]: {
    enUS: "Ral Rune",
    "zhTW": "符文：拉爾",
    "deDE": "[fs]Ral-Rune",
    "esES": "Runa Ral",
    "frFR": "[fs]Rune Ral",
    "itIT": "[fs]Runa Ral",
    "koKR": "랄 룬",
    "plPL": "Runa Ral",
    "esMX": "Runa Ral",
    "jaJP": "ラル・ルーン",
    "ptBR": "Runa Ral",
    "ruRU": "Руна Рал",
    "zhCN": "拉尔符文"
  },
  [ERune.Ort]: {
    enUS: "Ort Rune",
    "zhTW": "符文：歐特",
    "deDE": "[fs]Ort-Rune",
    "esES": "Runa Ort",
    "frFR": "[fs]Rune Ort",
    "itIT": "[fs]Runa Ort",
    "koKR": "오르트 룬",
    "plPL": "Runa Ort",
    "esMX": "Runa Ort",
    "jaJP": "オルト・ルーン",
    "ptBR": "Runa Ort",
    "ruRU": "Руна Орт",
    "zhCN": "欧特符文"
  },
  [ERune.Thul]: {
    enUS: "Thul Rune",
    "zhTW": "符文：書爾",
    "deDE": "[fs]Thul-Rune",
    "esES": "Runa Thul",
    "frFR": "[fs]Rune Thul",
    "itIT": "[fs]Runa Thul",
    "koKR": "주울 룬",
    "plPL": "Runa Thul",
    "esMX": "Runa Thul",
    "jaJP": "スル・ルーン",
    "ptBR": "Runa Thul",
    "ruRU": "Руна Тул",
    "zhCN": "图尔符文"
  },
  [ERune.Amn]: {
    enUS: "Amn Rune",
    "zhTW": "符文：安姆",
    "deDE": "[fs]Amn-Rune",
    "esES": "Runa Amn",
    "frFR": "[fs]Rune Amn",
    "itIT": "[fs]Runa Amn",
    "koKR": "앰 룬",
    "plPL": "Runa Amn",
    "esMX": "Runa Amn",
    "jaJP": "アムン・ルーン",
    "ptBR": "Runa Amn",
    "ruRU": "Руна Амн",
    "zhCN": "安姆符文"
  },
  [ERune.Sol]: {
    enUS: "Sol Rune",
    "zhTW": "符文：索爾",
    "deDE": "[fs]Sol-Rune",
    "esES": "Runa Sol",
    "frFR": "[fs]Rune Sol",
    "itIT": "[fs]Runa Sol",
    "koKR": "솔 룬",
    "plPL": "Runa Sol",
    "esMX": "Runa Sol",
    "jaJP": "ソル・ルーン",
    "ptBR": "Runa Sol",
    "ruRU": "Руна Сол",
    "zhCN": "索尔符文"
  },
  [ERune.Shael]: {
    enUS: "Shael Rune",
    "zhTW": "符文：夏",
    "deDE": "[fs]Shael-Rune",
    "esES": "Runa Shael",
    "frFR": "[fs]Rune Shael",
    "itIT": "[fs]Runa Shael",
    "koKR": "샤엘 룬",
    "plPL": "Runa Shael",
    "esMX": "Runa Shael",
    "jaJP": "シャエル・ルーン",
    "ptBR": "Runa Shael",
    "ruRU": "Руна Шаэль",
    "zhCN": "沙伊符文"
  },
  [ERune.Dol]: {
    enUS: "Dol Rune",
    "zhTW": "符文：多爾",
    "deDE": "[fs]Dol-Rune",
    "esES": "Runa Dol",
    "frFR": "[fs]Rune Dol",
    "itIT": "[fs]Runa Dol",
    "koKR": "돌 룬",
    "plPL": "Runa Dol",
    "esMX": "Runa Dol",
    "jaJP": "ドル・ルーン",
    "ptBR": "Runa Dol",
    "ruRU": "Руна Дол",
    "zhCN": "多尔符文"
  },
  [ERune.Hel]: {
    enUS: "Hel Rune",
    "zhTW": "符文：海爾",
    "deDE": "[fs]Hel-Rune",
    "esES": "Runa Hel",
    "frFR": "[fs]Rune Hel",
    "itIT": "[fs]Runa Hel",
    "koKR": "헬 룬",
    "plPL": "Runa Hel",
    "esMX": "Runa Hel",
    "jaJP": "ヘル・ルーン",
    "ptBR": "Runa Hel",
    "ruRU": "Руна Хел",
    "zhCN": "海尔符文"
  },
  [ERune.Io]: {
    enUS: "Io Rune",
    "zhTW": "符文：埃歐",
    "deDE": "[fs]Io-Rune",
    "esES": "Runa Io",
    "frFR": "[fs]Rune Io",
    "itIT": "[fs]Runa Io",
    "koKR": "이오 룬",
    "plPL": "Runa Io",
    "esMX": "Runa Io",
    "jaJP": "イオ・ルーン",
    "ptBR": "Runa Io",
    "ruRU": "Руна Ио",
    "zhCN": "艾欧符文"
  },
  [ERune.Lum]: {
    enUS: "Lum Rune",
    "zhTW": "符文：盧姆",
    "deDE": "[fs]Lum-Rune",
    "esES": "Runa Lum",
    "frFR": "[fs]Rune Lum",
    "itIT": "[fs]Runa Lum",
    "koKR": "룸 룬",
    "plPL": "Runa Lum",
    "esMX": "Runa Lum",
    "jaJP": "ラム・ルーン",
    "ptBR": "Runa Lum",
    "ruRU": "Руна Лум",
    "zhCN": "卢姆符文"
  },
  [ERune.Ko]: {
    enUS: "Ko Rune",
    "zhTW": "符文：科",
    "deDE": "[fs]Ko-Rune",
    "esES": "Runa Ko",
    "frFR": "[fs]Rune Ko",
    "itIT": "[fs]Runa Ko",
    "koKR": "코 룬",
    "plPL": "Runa Ko",
    "esMX": "Runa Ko",
    "jaJP": "コー・ルーン",
    "ptBR": "Runa Ko",
    "ruRU": "Руна Ко",
    "zhCN": "科符文"
  },
  [ERune.Fal]: {
    enUS: "Fal Rune",
    "zhTW": "符文：法爾",
    "deDE": "[fs]Fal-Rune",
    "esES": "Runa Fal",
    "frFR": "[fs]Rune Fal",
    "itIT": "[fs]Runa Fal",
    "koKR": "팔 룬",
    "plPL": "Runa Fal",
    "esMX": "Runa Fal",
    "jaJP": "ファル・ルーン",
    "ptBR": "Runa Fal",
    "ruRU": "Руна Фал",
    "zhCN": "法尔符文"
  },
  [ERune.Lem]: {
    enUS: "Lem Rune",
    ruRU: "Руна Лем",
    "zhTW": "符文：藍姆",
    "deDE": "[fs]Lem-Rune",
    "esES": "Runa Lem",
    "frFR": "[fs]Rune Lem",
    "itIT": "[fs]Runa Lem",
    "koKR": "렘 룬",
    "plPL": "Runa Lem",
    "esMX": "Runa Lem",
    "jaJP": "レム・ルーン",
    "ptBR": "Runa Lem",
    "zhCN": "兰姆符文"
  },
  [ERune.Pul]: {
    enUS: "Pul Rune",
    "zhTW": "符文：普爾",
    "deDE": "[fs]Pul-Rune",
    "esES": "Runa Pul",
    "frFR": "[fs]Rune Pul",
    "itIT": "[fs]Runa Pul",
    "koKR": "풀 룬",
    "plPL": "Runa Pul",
    "esMX": "Runa Pul",
    "jaJP": "プル・ルーン",
    "ptBR": "Runa Pul",
    "ruRU": "Руна Пул",
    "zhCN": "普尔符文"
  },
  [ERune.Um]: {
    enUS: "Um Rune",
    "zhTW": "符文：烏姆",
    "deDE": "[fs]Um-Rune",
    "esES": "Runa Um",
    "frFR": "[fs]Rune Um",
    "itIT": "[fs]Runa Um",
    "koKR": "우움 룬",
    "plPL": "Runa Um",
    "esMX": "Runa Um",
    "jaJP": "アム・ルーン",
    "ptBR": "Runa Um",
    "ruRU": "Руна Ум",
    "zhCN": "乌姆符文"
  },
  [ERune.Mal]: {
    enUS: "Mal Rune",
    "zhTW": "符文：馬爾",
    "deDE": "[fs]Mal-Rune",
    "esES": "Runa Mal",
    "frFR": "[fs]Rune Mal",
    "itIT": "[fs]Runa Mal",
    "koKR": "말 룬",
    "plPL": "Runa Mal",
    "esMX": "Runa Mal",
    "jaJP": "マル・ルーン",
    "ptBR": "Runa Mal",
    "ruRU": "Руна Мал",
    "zhCN": "玛尔符文"
  },
  [ERune.Ist]: {
    enUS: "Ist Rune",
    "zhTW": "符文：伊司特",
    "deDE": "[fs]Ist-Rune",
    "esES": "Runa Ist",
    "frFR": "[fs]Rune Ist",
    "itIT": "[fs]Runa Ist",
    "koKR": "이스트 룬",
    "plPL": "Runa Ist",
    "esMX": "Runa Ist",
    "jaJP": "イスト・ルーン",
    "ptBR": "Runa Ist",
    "ruRU": "Руна Ист",
    "zhCN": "伊司特符文"
  },
  [ERune.Gul]: {
    enUS: "Gul Rune",
    "zhTW": "符文：古爾",
    "deDE": "[fs]Gul-Rune",
    "esES": "Runa Gul",
    "frFR": "[fs]Rune Gul",
    "itIT": "[fs]Runa Gul",
    "koKR": "굴 룬",
    "plPL": "Runa Gul",
    "esMX": "Runa Gul",
    "jaJP": "ガル・ルーン",
    "ptBR": "Runa Gul",
    "ruRU": "Руна Гул",
    "zhCN": "古尔符文"
  },
  [ERune.Vex]: {
    enUS: "Vex Rune",
    "zhTW": "符文：伐克斯",
    "deDE": "[fs]Vex-Rune",
    "esES": "Runa Vex",
    "frFR": "[fs]Rune Vex",
    "itIT": "[fs]Runa Vex",
    "koKR": "벡스 룬",
    "plPL": "Runa Vex",
    "esMX": "Runa Vex",
    "jaJP": "ヴェックス・ルーン",
    "ptBR": "Runa Vex",
    "ruRU": "Руна Векс",
    "zhCN": "伐克斯符文"
  },
  [ERune.Ohm]: {
    enUS: "Ohm Rune",
    "zhTW": "符文：歐姆",
    "deDE": "[fs]Ohm-Rune",
    "esES": "Runa Ohm",
    "frFR": "[fs]Rune Ohm",
    "itIT": "[fs]Runa Ohm",
    "koKR": "오움 룬",
    "plPL": "Runa Ohm",
    "esMX": "Runa Ohm",
    "jaJP": "オーム・ルーン",
    "ptBR": "Runa Ohm",
    "ruRU": "Руна Ом",
    "zhCN": "欧姆符文"
  },
  [ERune.Lo]: {
    enUS: "Lo Rune",
    "zhTW": "符文：羅",
    "deDE": "[fs]Lo-Rune",
    "esES": "Runa Lo",
    "frFR": "[fs]Rune Lo",
    "itIT": "[fs]Runa Lo",
    "koKR": "로 룬",
    "plPL": "Runa Lo",
    "esMX": "Runa Lo",
    "jaJP": "ロー・ルーン",
    "ptBR": "Runa Lo",
    "ruRU": "Руна Ло",
    "zhCN": "罗符文"
  },
  [ERune.Sur]: {
    enUS: "Sur Rune",
    "zhTW": "符文：瑟",
    "deDE": "[fs]Sur-Rune",
    "esES": "Runa Sur",
    "frFR": "[fs]Rune Sur",
    "itIT": "[fs]Runa Sur",
    "koKR": "수르 룬",
    "plPL": "Runa Sur",
    "esMX": "Runa Sur",
    "jaJP": "サー・ルーン",
    "ptBR": "Runa Sur",
    "ruRU": "Руна Сур",
    "zhCN": "瑟符文"
  },
  [ERune.Ber]: {
    enUS: "Ber Rune",
    "zhTW": "符文：貝",
    "deDE": "[fs]Ber-Rune",
    "esES": "Runa Ber",
    "frFR": "[fs]Rune Ber",
    "itIT": "[fs]Runa Ber",
    "koKR": "베르 룬",
    "plPL": "Runa Ber",
    "esMX": "Runa Ber",
    "jaJP": "バー・ルーン",
    "ptBR": "Runa Ber",
    "ruRU": "Руна Бер",
    "zhCN": "贝符文"
  },
  [ERune.Jah]: {
    enUS: "Jah Rune",
    "zhTW": "符文：喬",
    "deDE": "[fs]Jah-Rune",
    "esES": "Runa Jah",
    "frFR": "[fs]Rune Jah",
    "itIT": "[fs]Runa Jah",
    "koKR": "자 룬",
    "plPL": "Runa Jah",
    "esMX": "Runa Jah",
    "jaJP": "ジャー・ルーン",
    "ptBR": "Runa Jah",
    "ruRU": "Руна Джа",
    "zhCN": "扎哈符文"
  },
  [ERune.Cham]: {
    enUS: "Cham Rune",
    "zhTW": "符文：查姆",
    "deDE": "[fs]Cham-Rune",
    "esES": "Runa Cham",
    "frFR": "[fs]Rune Cham",
    "itIT": "[fs]Runa Cham",
    "koKR": "참 룬",
    "plPL": "Runa Cham",
    "esMX": "Runa Cham",
    "jaJP": "チャム・ルーン",
    "ptBR": "Runa Cham",
    "ruRU": "Руна Чам",
    "zhCN": "查姆符文"
  },
  [ERune.Zod]: {
    enUS: "Zod Rune",
    "zhTW": "符文：薩德",
    "deDE": "[fs]Zod-Rune",
    "esES": "Runa Zod",
    "frFR": "[fs]Rune Zod",
    "itIT": "[fs]Runa Zod",
    "koKR": "조드 룬",
    "plPL": "Runa Zod",
    "esMX": "Runa Zod",
    "jaJP": "ゾッド・ルーン",
    "ptBR": "Runa Zod",
    "ruRU": "Руна Зод",
    "zhCN": "佐德符文"
  },
}