
export enum ERune {
    'El' = 'el',
    'Eld' = 'eld',
    'Tir' = 'tir',
    'Nef' = 'nef',
    'Eth' = 'eth',
    'Ith' = 'ith',
    'Tal' = 'tal',
    'Ral' = 'ral',
    'Ort' = 'ort',
    'Thul' = 'thul',
    'Amn' = 'amn',
    'Sol' = 'sol',
    'Shael' = 'shael',
    'Dol' = 'dol',
    'Hel' = 'hel',
    'Io' = 'io',
    'Lum' = 'lum',
    'Ko' = 'ko',
    'Fal' = 'fal',
    'Lem' = 'lem',
    'Pul' = 'pul',
    'Um' = 'um',
    'Mal' = 'mal',
    'Ist' = 'ist',
    'Gul' = 'gul',
    'Vex' = 'vex',
    'Ohm' = 'ohm',
    'Lo' = 'lo',
    'Sur' = 'sur',
    'Ber' = 'ber',
    'Jah' = 'jah',
    'Cham' = 'cham',
    'Zod' = 'zod'
}


export const runes = [
    ERune.El,
    ERune.Eld,
    ERune.Tir,
    ERune.Nef,
    ERune.Eth,
    ERune.Ith,
    ERune.Tal,
    ERune.Ral,
    ERune.Ort,
    ERune.Thul,
    ERune.Amn,
    ERune.Sol,
    ERune.Shael,
    ERune.Dol,
    ERune.Hel,
    ERune.Io,
    ERune.Lum,
    ERune.Ko,
    ERune.Fal,
    ERune.Lem,
    ERune.Pul,
    ERune.Um,
    ERune.Mal,
    ERune.Ist,
    ERune.Gul,
    ERune.Vex,
    ERune.Ohm,
    ERune.Lo,
    ERune.Sur,
    ERune.Ber,
    ERune.Jah,
    ERune.Cham,
    ERune.Zod
] as const;


export const runeMinLvl = {
    [ERune.El]: 11,
    [ERune.Eld]: 11,
    [ERune.Tir]: 13,
    [ERune.Nef]: 13,
    [ERune.Eth]: 15,
    [ERune.Ith]: 15,
    [ERune.Tal]: 17,
    [ERune.Ral]: 19,
    [ERune.Ort]: 21,
    [ERune.Thul]: 23,
    [ERune.Amn]: 25,
    [ERune.Sol]: 27,
    [ERune.Shael]: 29,
    [ERune.Dol]: 31,
    [ERune.Hel]: 0,
    [ERune.Io]: 35,
    [ERune.Lum]: 37,
    [ERune.Ko]: 39,
    [ERune.Fal]: 41,
    [ERune.Lem]: 43,
    [ERune.Pul]: 45,
    [ERune.Um]: 47,
    [ERune.Mal]: 49,
    [ERune.Ist]: 51,
    [ERune.Gul]: 53,
    [ERune.Vex]: 55,
    [ERune.Ohm]: 57,
    [ERune.Lo]: 59,
    [ERune.Sur]: 61,
    [ERune.Ber]: 63,
    [ERune.Jah]: 65,
    [ERune.Cham]: 67,
    [ERune.Zod]: 69,
}

export const idToRuneMapper: Record<number, ERune> = {
    10902: ERune.Io,
    10904: ERune.Shael,
    10906: ERune.Jah,
    20440: ERune.Zod,
    20441: ERune.Cham,
    20443: ERune.Ber,
    20444: ERune.Sur,
    20445: ERune.Lo,
    20446: ERune.Ohm,
    20447: ERune.Vex,
    20448: ERune.Gul,
    20449: ERune.Ist,
    20450: ERune.Mal,
    20451: ERune.Um,
    20452: ERune.Pul,
    20453: ERune.Lem,
    20454: ERune.Fal,
    20455: ERune.Ko,
    20456: ERune.Lum,
    20458: ERune.Hel,
    20459: ERune.Dol,
    20461: ERune.Sol,
    20462: ERune.Amn,
    20463: ERune.Thul,
    20464: ERune.Ort,
    20465: ERune.Ral,
    20466: ERune.Tal,
    20467: ERune.Ith,
    20468: ERune.Eth,
    20469: ERune.Nef,
    20470: ERune.Tir,
    20471: ERune.Eld,
    20472: ERune.El,
}

export const runeNumbers = {
    [ERune.El]: 1,
    [ERune.Eld]: 2,
    [ERune.Tir]: 3,
    [ERune.Nef]: 4,
    [ERune.Eth]: 5,
    [ERune.Ith]: 6,
    [ERune.Tal]: 7,
    [ERune.Ral]: 8,
    [ERune.Ort]: 9,
    [ERune.Thul]: 10,
    [ERune.Amn]: 11,
    [ERune.Sol]: 12,
    [ERune.Shael]: 13,
    [ERune.Dol]: 14,
    [ERune.Hel]: 15,
    [ERune.Io]: 16,
    [ERune.Lum]: 17,
    [ERune.Ko]: 18,
    [ERune.Fal]: 19,
    [ERune.Lem]: 20,
    [ERune.Pul]: 21,
    [ERune.Um]: 22,
    [ERune.Mal]: 23,
    [ERune.Ist]: 24,
    [ERune.Gul]: 25,
    [ERune.Vex]: 26,
    [ERune.Ohm]: 27,
    [ERune.Lo]: 28,
    [ERune.Sur]: 29,
    [ERune.Ber]: 30,
    [ERune.Jah]: 31,
    [ERune.Cham]: 32,
    [ERune.Zod]: 33,
}